### ISSUE TITLE
Deprecation warnings encountered

### ISSUE THREAD

**Issue by noqcks** [telusdigital/ansible-python#6]
I ran into this while using this ansible role.

```
       TASK [telusdigital.python : Install Packages | apt | build dependencies] *******
       [DEPRECATION WARNING]: Using bare variables is deprecated. Update your playbooks
        so that the environment value uses the full variable syntax 
       ('{{python_build_dependencies}}'). This feature will be removed in a future 
       release. Deprecation warnings can be disabled by setting 
       deprecation_warnings=False in ansible.cfg.
```
I believe that this
```
- name: Install Packages | apt | build dependencies
  apt:
    state: latest
    name: "{{ item }}"
  with_items: python_build_dependencies
  when: python_build_dependencies
  tags:
    - software-installation
    - using-apt
    - python
```

should be like this
```
- name: Install Packages | apt | build dependencies
  apt:
    state: latest
    name: "{{ item }}"
  with_items: "{{ python_build_dependencies }}"
  when: python_build_dependencies
  tags:
    - software-installation
    - using-apt
    - python
```
